coverage:
  status:
    project:
      default:
        target: auto
        threshold: 70%

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
  individual_components:
    - component_id: core
      name: core
      paths:
        - packages/core/src/bio_analyze_core
    - component_id: plot
      name: plot
      paths:
        - packages/plot/src/bio_analyze_plot
    - component_id: docking
      name: docking
      paths:
        - packages/docking/src/bio_analyze_docking
    - component_id: rna_seq
      name: rna_seq
      paths:
        - packages/rna_seq/src/bio_analyze_rna_seq
    - component_id: cli
      name: cli
      paths:
        - packages/cli/src/bio_analyze_cli
    - component_id: msa
      name: msa
      paths:
        - packages/msa/src/bio_analyze_msa
