name: CI

permissions:
    contents: write
    checks: write
    pull-requests: write

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11", "3.12"]
            fail-fast: false

        steps:
            - uses: actions/checkout@v4

            - name: Set up Micromamba
              uses: mamba-org/setup-micromamba@v1
              with:
                  environment-name: bio-analyze-env
                  create-args: >-
                      python=${{ matrix.python-version }}
                  condarc: |
                      channels:
                        - conda-forge
                        - bioconda
                        - defaults
                      channel_priority: strict
                  init-shell: bash
                  cache-environment: true
                  post-cleanup: "all"

            - name: Install System Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgl1 libglib2.0-0 fonts-wqy-microhei fonts-wqy-zenhei fonts-dejavu-core fonts-dejavu-extra ttf-mscorefonts-installer curl git build-essential

            - name: Install Conda Dependencies
              run: |
                  micromamba install -y -n bio-analyze-env \
                    fastp \
                    salmon \
                    fastqc \
                    star \
                    samtools \
                    gffread \
                    sra-tools \
                    pdbfixer \
                    vina \
                    meeko \
                    propka \
                    openbabel \
                    rdkit \
                    six \
                    pymol-open-source \
                    gemmi \
                    hatchling

                  micromamba clean -afy

            - name: Install External Binaries (Gnina/Smina)
              run: |
                  sudo curl -L https://github.com/gnina/gnina/releases/download/v1.0.3/gnina -o /usr/local/bin/gnina
                  sudo chmod +x /usr/local/bin/gnina
                  sudo curl -L https://sourceforge.net/projects/smina/files/smina.static/download -o /usr/local/bin/smina
                  sudo chmod +x /usr/local/bin/smina

            - name: Install Project Packages Locally
              shell: bash -el {0}
              run: |
                  # Install packages in editable mode using pip
                  python -m pip install --upgrade pip
                  pip install -e packages/core
                  pip install -e packages/plot
                  pip install -e packages/docking
                  pip install -e packages/rna_seq
                  pip install -e packages/cli
                  pip install pytest \
                    pytest-cov \
                    pytest-sugar \
                    pytest-clarity \
                    pytest-timeout \
                    pytest-regressions \
                    allure-pytest \
                    pillow
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
              if: failure()

            - name: Run Tests
              shell: bash -el {0}
              run: |
                  pytest packages --timeout=60 --junit-xml pytest.xml --alluredir=allure-results-${{ matrix.python-version }} --clean-alluredir

            - name: Upload Test Results
              if: (!cancelled())
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
              with:
                  name: Test Results (Python ${{ matrix.python-version }})
                  path: pytest.xml

            - name: Upload Allure Results
              if: (!cancelled())
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
              with:
                  name: allure-results-${{ matrix.python-version }}
                  path: allure-results-${{ matrix.python-version }}
                  retention-days: 7

    publish-test-results:
        name: "Publish Tests Results"
        needs: test
        runs-on: ubuntu-latest

        if: (!cancelled())

        steps:
            - name: Checkout gh-pages (for history)
              uses: actions/checkout@v4
              with:
                ref: gh-pages
                path: gh-pages
                continue-on-error: true

            - name: Download Artifacts
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
              with:
                  path: artifacts

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                  files: "artifacts/**/*.xml"

            - name: Download Allure Results(3.9)
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
              with:
                  name: allure-results-3.9
                  path: merged-results/3.9
            
            - name: Download Allure Results(3.10)
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
              with:
                  name: allure-results-3.10
                  path: merged-results/3.10
            
            - name: Download Allure Results(3.11)
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
              with:
                  name: allure-results-3.11
                  path: merged-results/3.11
            
            - name: Download Allure Results(3.12)
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
              with:
                  name: allure-results-3.12
                  path: merged-results/3.12

            - name: Copy History Trend
              run: |
                if [ -d "gh-pages/history" ]; then
                  mkdir -p merged-results/history
                  cp -r gh-pages/history/* merged-results/history/
                fi

            - name: Upload Merged Results
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
              with:
                  name: allure-results-merged
                  path: merged-results
    deploy-report:
        name: "Deploy Allure Report"
        needs: publish-test-results
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deploy.outputs.page_url }}

        if: (!cancelled())

        steps:

            - name: Download Merged Results
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
              with:
                  name: allure-results-merged
                  path: merged-results

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              with:
                  allure-results: merged-results
                  allure-report: allure-report
            - name: Deploy to GitHub Pages
              id: deployment
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: allure-report
